# Generated by Django 4.1.2 on 2022-10-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Init_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='uploads/')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1900)),
                ('is_img_search', models.BooleanField()),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prompt_designer.init_img')),
            ],
        ),
    ]
