# Generated by Django 4.1.2 on 2022-10-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diffusion_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=256)),
                ('hf_repo_location', models.CharField(max_length=512)),
                ('revision', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Init_Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='uploads/')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=1900)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('diff_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.diffusion_model')),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.init_img')),
            ],
        ),
    ]
