# Generated by Django 4.1.2 on 2022-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_prompt_complete_date_prompt_is_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='websocket',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
