# Generated by Django 4.1.2 on 2022-11-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prompt_websocket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='websocket',
            new_name='websocket_guid',
        ),
    ]
